teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.150
    scale_linear_turbo:
      x: 0.460   # Turbo = slow in this config. 

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 0.25
    scale_angular_turbo:
      yaw: 0.5     # slower turning for when going forward fast

    enable_button: 4  # Left Front button
    enable_turbo_button: 5  # Right Front button
